package Lexical;

/**
 * 单词类别
 */
public enum TokenType {
	IDENFR, INTCON, STRCON, MAINTK, CONSTTK, INTTK, BREAKTK, CONTINUETK,
	IFTK, ELSETK, NOT, AND, OR, FORTK, GETINTTK, PRINTFTK, RETURNTK,
	PLUS, MINU, VOIDTK, MULT, DIV, MOD, LSS, LEQ, GRE, GEQ, EQL,
	NEQ, ASSIGN, SEMICN, COMMA, LPARENT, RPARENT, LBRACK, RBRACK,
	LBRACE, RBRACE
}
